[mgr]
ratio = [2, 4, 3]

sort_by = "natural"
sort_sensitive = false
sort_reverse = false
sort_dir_first = true 
sort_translit = true

linemode = "size"

show_hidden = true
show_symlink = true

scroll_off = 5

[preview]
wrap = "yes"
tab_size = 4

[open]
rules = [
    { name = "*", use = "open"}
]